import { BOSS_CATEGORY, DROPS_BUCKET } from '../wiki/fields.js'
import type { FetchManifest } from '../snapshots/store.js'
import { MIN_MAIN_TABLE_ROWS, TIERS, TIER_LABELS, type Tier, type TriageResult } from './classify.js'

function escapePipes(value: string): string {
  return value.replace(/\|/g, '\\|')
}

export function renderTriageMarkdown(
  manifest: FetchManifest,
  results: readonly TriageResult[],
  counts: ReadonlyMap<Tier, number>
): string {
  const total = results.length
  const share = (count: number): string =>
    total === 0 ? '0.0%' : `${((count / total) * 100).toFixed(1)}%`

  const lines: string[] = []

  lines.push('# Triage')
  lines.push('')
  lines.push(
    'Generated by `pnpm ingest triage` from the snapshots in `data/snapshots/`. ' +
      'Do not edit by hand — re-run the command.'
  )
  lines.push('')
  lines.push(`- Inventory source: \`${BOSS_CATEGORY}\` (${manifest.entries.length} pages)`)
  lines.push(`- Drop rows: \`bucket('${DROPS_BUCKET}')\``)
  lines.push(`- Fetched: ${manifest.fetchedAt}`)
  lines.push(`- User-Agent: \`${manifest.userAgent}\``)
  lines.push(`- Requests in the fetch run: ${manifest.requestCount}`)
  lines.push('')
  lines.push(
    'This is triage, not parsing. Nothing here produces a canonical `Table`, `Node` or ' +
      '`Rate`; it classifies each page by how much machinery it will need.'
  )
  lines.push('')

  lines.push('## Tier distribution')
  lines.push('')
  lines.push('| Tier | Pages | Share | Meaning | Lands in |')
  lines.push('|---|---:|---:|---|---|')
  const landing: Record<Tier, string> = {
    A: 'Phase 2 parser',
    B: 'Phase 2 parser + conditions',
    C: 'Phase 3 shared tables',
    D: 'Phase 5 review/override',
    E: 'Phase 5 override',
  }
  for (const tier of TIERS) {
    const count = counts.get(tier) ?? 0
    lines.push(
      `| **${tier}** | ${count} | ${share(count)} | ${TIER_LABELS[tier]} | ${landing[tier]} |`
    )
  }
  lines.push(`| | **${total}** | | | |`)
  lines.push('')

  lines.push('## How a tier is decided')
  lines.push('')
  lines.push('Highest applicable tier wins, checked in this order:')
  lines.push('')
  lines.push(
    `1. **E** — zero \`dropsline\` rows, every row is \`Always\`, or no denominator group ` +
      `reaches ${MIN_MAIN_TABLE_ROWS} rows. There is no main weighted table on the page; ` +
      `the real loot table lives on a reward-chest or raid page.`
  )
  lines.push(
    '2. **D** — the bucket errored, a rarity is neither a fraction nor `Always`, or the ' +
      'main table overflows its denominator and a membership split does not fix it.'
  )
  lines.push('3. **C** — otherwise fine, but at least one row is flagged `rare_drop_table`.')
  lines.push('4. **B** — carries `(m)` / `(f)` markers, or only the membership split fits.')
  lines.push('5. **A** — the main table fits its denominator, no markers, no shared tables.')
  lines.push('')
  lines.push('Two rules do most of the work here, and both matter:')
  lines.push('')
  lines.push(
    `- **The main table is the denominator group with the most rows**, and it must carry ` +
      `at least ${MIN_MAIN_TABLE_ROWS} rows to count as one. Smaller groups are pre-roll ` +
      `or tertiary drops, which never sum to their denominators and are not judged as if ` +
      `they should.`
  )
  lines.push(
    '- **Summing *under* the denominator is not a defect.** Section 4.3 makes the ' +
      'remainder of a weighted table an implicit `nothing`, so a shortfall is expected. ' +
      'Only *overflowing* the denominator is evidence of a problem — that is the Brutus ' +
      'case, where members and free-to-play rows are interleaved into one rendered table.'
  )
  lines.push('')

  for (const tier of TIERS) {
    const inTier = results.filter((result) => result.tier === tier)
    if (inTier.length === 0) continue
    lines.push(`## Tier ${tier} — ${TIER_LABELS[tier]} (${inTier.length})`)
    lines.push('')
    lines.push('| Page | Rows | Main den. | Markers | RDT | Notes |')
    lines.push('|---|---:|---:|:-:|:-:|---|')
    for (const result of inTier) {
      lines.push(
        `| ${escapePipes(result.title)} | ${result.rowCount} | ` +
          `${result.mainDenominator ?? '—'} | ${result.hasVariantMarkers ? 'yes' : ''} | ` +
          `${result.hasRareDropTable ? 'yes' : ''} | ${escapePipes(result.reasons.join('; '))} |`
      )
    }
    lines.push('')
  }

  const drift = results.filter((result) => result.driftKeys.length > 0)
  if (drift.length > 0) {
    lines.push('## Schema drift')
    lines.push('')
    lines.push('`drop_json` keys not declared in `apps/ingest/src/wiki/fields.ts`:')
    lines.push('')
    const keys = new Map<string, number>()
    for (const result of drift) {
      for (const key of result.driftKeys) keys.set(key, (keys.get(key) ?? 0) + 1)
    }
    for (const [key, count] of [...keys].sort((a, b) => b[1] - a[1])) {
      lines.push(`- \`${key}\` — on ${count} pages`)
    }
    lines.push('')
  }

  return `${lines.join('\n')}\n`
}
