export {
  BossSchema,
  BossSourceSchema,
  BossStatusSchema,
  ConditionSchema,
  DEFAULT_SIM_CONTEXT,
  DERIVED_CONTEXT_FIELDS,
  EntrySchema,
  FORMULA_IDS,
  FormulaIdSchema,
  FormulaRefSchema,
  LeafEntrySchema,
  LeafNodeSchema,
  MultiplierSchema,
  NodeSchema,
  OwnershipGateSchema,
  PartialSimContextSchema,
  QtyRoundingSchema,
  QtySpecSchema,
  QTY_ROUNDING_MODES,
  RateSchema,
  SharedTableSchema,
  SimContextSchema,
  TABLE_MODES,
  TableModeSchema,
  TableSchema,
  VALIDATION_CHECKS,
  ValidationCheckSchema,
  ValidationResultSchema,
  type Boss,
  type BossInput,
  type BossSource,
  type BossStatus,
  type Condition,
  type Entry,
  type FormulaId,
  type FormulaRef,
  type LeafEntry,
  type LeafNode,
  type Multiplier,
  type Node,
  type OwnershipGate,
  type PartialSimContext,
  type QtyRounding,
  type QtySpec,
  type Rate,
  type SharedTable,
  type SimContext,
  type SimContextField,
  type Table,
  type TableMode,
  type ValidationCheck,
  type ValidationResult,
} from './schema.js'

export {
  conditionsHold,
  entryApplies,
  evaluateCondition,
  resolveSimContext,
  withDerivedContext,
} from './conditions.js'

export {
  createFormulaRegistry,
  defaultFormulaRegistry,
  FORMULA_CONTEXT_FIELDS,
  evaluateFormula,
  evaluateMultiplier,
  evaluateQuantity,
  evaluateWeight,
  FormulaNotImplementedError,
  IMPLEMENTED_FORMULA_IDS,
  rateToProbability,
  // Tombs of Amascut's rule set, exported so `apps/ingest/test/toa.test.ts`
  // can assert it against the wiki's own published figures rather than
  // re-implementing the arithmetic it is supposed to be checking.
  TOA_DUNG_GATE_POINTS,
  TOA_ELITE_CLUE_DENOMINATOR,
  TOA_ELITE_CLUE_RATE_CAP,
  TOA_OUT_OF_RANGE_DIVISOR,
  TOA_UNIQUE_RATE_CAP,
  TOA_UNIQUES,
  toaAdjustedRaidLevel,
  toaAdjustedRaidLevelPet,
  toaCommonQtyScale,
  toaReweightedUniques,
  toaUniqueRate,
  toaUniqueWeight,
  UnknownFormulaError,
  ZALCANO_DROP_ELIGIBILITY_SHIELD_DAMAGE,
  ZALCANO_UNIQUE_ELIGIBILITY_TOTAL_DAMAGE,
  type FormulaFn,
  type FormulaRegistry,
  type ToaUnique,
} from './formulas.js'

export { mulberry32, type Rng } from './rng.js'

export {
  applyQtyMultiplier,
  CircularTableRefError,
  compileBoss,
  effectiveWeightedPool,
  meanScaledQty,
  ownershipGateSatisfied,
  UnresolvedTableRefError,
  WeightsExceedDenominatorError,
  type CompiledBoss,
  type CompiledNode,
  type CompiledRolls,
  type CompiledTable,
  type CompileOptions,
  type EffectivePool,
  type ResolvedQtySpec,
} from './compile.js'

export {
  DEFAULT_LOG_LIMIT,
  simulate,
  type DropTally,
  type KillLogDrop,
  type KillLogEntry,
  type PriceLookup,
  type SimOptions,
  type SimResult,
} from './simulate.js'

export {
  expectedValue,
  MAX_WITHOUT_REPLACEMENT_ROLLS,
  UnsupportedExpectedValueError,
  type ExpectedItem,
  type ExpectedValueOptions,
  type ExpectedValueResult,
} from './expected-value.js'
